# Generated by Django 2.2.7 on 2020-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitemmodel',
            name='title_img',
            field=models.ImageField(default='guide/default.jpg', upload_to='guide/%Y/%m/%d'),
        ),
    ]
