# Generated by Django 2.2.7 on 2020-10-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitemmodel',
            name='now_person',
            field=models.IntegerField(default=0),
        ),
    ]
