# Generated by Django 2.2.7 on 2020-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitemmodel',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tripitemmodel',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
