# Generated by Django 2.2.7 on 2020-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/media/profile/default.jpg', upload_to='profile/', verbose_name='프로필사진'),
        ),
    ]
