# Generated by Django 2.2.7 on 2020-10-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_cup',
            field=models.BooleanField(default=False),
        ),
    ]
